export const carreras = [
    'Ingeniería de Software',
    'Ingeniería de Sistemas de Información',
    'Ingeniería de Sistemas',
    'Ciencia de la Computación',
    'Ingeniería Civil',
    'Ingeniería Industrial',
    'Ingeniería Empresarial',
    'Administración',
    'Marketing',
    'Contabilidad',
    'Economía',
    'Arquitectura',
    'Diseño Gráfico',
    'Diseño de Interiores',
    'Comunicación Audiovisual',
    'Periodismo',
    'Derecho',
    'Psicología',
    'Medicina Humana',
    'Nutrición',
    'Terapia Física',
    'Ingeniería Electrónica',
    'Ingeniería Mecatrónica',
    'Ingeniería de Telecomunicaciones',
    'Ingeniería Ambiental',
    'Ingeniería de Minas',
    'Gastronomía',
    'Hotelería y Administración'
].sort();